# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "becorecode/alpinelinux-3.11"
  config.vm.box_version = "1.0.0"
  config.ssh.shell = "/bin/ash"

  config.vm.provider "vmware_fusion" do |v|
    v.clone_directory = "/Volumes/Fast Ext Disk/curso_redis/vagrant/replication"
    v.memory = 2500
  end
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2500
  end

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.158.10"
    master.vm.provision "shell", inline: <<-SHELL
      echo "Setting hostname to master"
      echo "master" > /etc/hostname
      hostname -F /etc/hostname
      echo "Install iproute2"
      # Para disponer del comando tc 
      apk add iproute2
      echo "Install fake2db"
      pip3 install --upgrade pip
      pip3 install redis fake2db
    SHELL
  end

  config.vm.define "replica" do |replica|
    replica.vm.network "private_network", ip: "192.168.158.11"
    replica.vm.provision "shell", inline: <<-SHELL
      echo "Setting hostname to replica"
      echo "replica" > /etc/hostname
      hostname -F /etc/hostname
    SHELL
  end
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: <<-SHELL
    rm -rf /usr/local/redis-random-data-generator /usr/local/curso-redis-para-administradores-de-sistemas
    apk add bvi util-linux terminus-font git redis nodejs npm bash python3 
    git clone https://github.com/SaminOz/redis-random-data-generator /usr/local/redis-random-data-generator
    git clone https://github.com/Be-Core-Code/curso-redis-para-administradores-de-sistemas /usr/local/curso-redis-para-administradores-de-sistemas
  SHELL
end
