# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "becorecode/alpinelinux-3.11"
  config.vm.box_version = "1.0.0"
  config.ssh.shell = "/bin/ash"

  config.vm.provider "vmware_fusion" do |v|
    v.clone_directory = "/Volumes/Fast Ext Disk/curso_redis/vagrant/cluster"
  end
  
  nodes = [
    {hostname: 'nodea', ip: '192.168.158.100'},  
    {hostname: 'nodeb', ip: '192.168.158.101'},  
    {hostname: 'nodec', ip: '192.168.158.102'}  
  ]
  nodes.each do |nodedata|
    config.vm.define nodedata[:hostname] do |node|
      node.vm.network "private_network", ip: nodedata[:ip]
      node.vm.provision "file", source: "redis-#{nodedata[:hostname]}-master.conf", destination: "$HOME/redis.conf"
      node.vm.provision "file", source: "redis-#{nodedata[:hostname]}-replica.conf", destination: "$HOME/redis-replica.conf"
      node.vm.provision "file", source: "redis-replica.rc", destination: "$HOME/redis-replica.rc"
      node.vm.provision "shell", inline: <<-SHELL
        echo "Setting overcommit_memory"
        echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf 
        sysctl vm.overcommit_memory=1
        echo "Setting hostname to #{nodedata[:hostname]}"
        echo "#{nodedata[:hostname]}" > /etc/hostname
        hostname -F /etc/hostname
        mv /home/vagrant/redis.conf /etc/redis.conf
        mv /home/vagrant/redis-replica.conf /etc/redis-replica.conf
        mv /home/vagrant/redis-replica.rc /etc/init.d/redis-replica
        chmod 644 /etc/redis.conf /etc/redis-replica.conf
        chmod 744 /etc/init.d/redis-replica
        chown root:root /etc/redis.conf /etc/redis-replica.conf /etc/init.d/redis-replica
        rc-update add redis default
        rc-update add redis-replica default
        rc-service redis start
        rc-service redis-replica start
      SHELL
  end

  end
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: <<-SHELL
    apk add bvi util-linux terminus-font git redis nodejs npm bash python3 
    rm -rf  /usr/local/redis-random-data-generator /usr/local/curso-redis-para-administradores-de-sistemas
    git clone https://github.com/SaminOz/redis-random-data-generator /usr/local/redis-random-data-generator
    git clone https://github.com/Be-Core-Code/curso-redis-para-administradores-de-sistemas /usr/local/curso-redis-para-administradores-de-sistemas
  SHELL
end
